### ISSUE TITLE
Installing UnNethack alerts as containing a trojen

### ISSUE THREAD

**Issue by blightor** [sboselli/loadrl#2]
What is the link for UnNethack that is used here.  In fact I think it would be good if you made all of the download link public, because I do not get a trojen warining when downloading UnNethack manually.

![image](https://user-images.githubusercontent.com/33708126/73708212-dfbf4a00-4751-11ea-9ce8-0f07870b93b2.png)

**Comment by Kyzrati** [comment]
According to loadRL's data it appears to be a direct link to the official UnNethack download, but indeed it gives a trojan warning when downloading via loadRL that does not occur when downloading directly from Sourceforge.

**Comment by blightor** [comment]
It seems to be pointing to a file that is slightly different to the Sourceforge version.

Please use "unnethack-win32-5.2.0-1.zip" instead of the unnethack-win32-5.2.0.zip

**Comment by Kyzrati** [comment]
Interestingly the president of SourceForge actually caught this on Twitter and was [looking into it](https://twitter.com/loganabbott/status/1224548140407087107) :P

**Comment by bhaak** [comment]
One binary in the zip had debug symbols compiled in and that triggered some heuristic with Microsoft Defender.

The unnethack-win32-5.2.0-1.zip has the same file with stripped debug symbols and passes the download check.

**Comment by Kyzrati** [comment]
Ah cool, good to know specifically what it was that caused that, something to remember when it comes to notifying people about false positives in indie games in the future :)

**Comment by sboselli** [comment]
Nice catch. Thank you all for the time and follow ups. Merging the PR with the updated version, since the release notes over at UnNetHack's Sourceforge confirm the findings:

```
2019-12-24  UnNetHack 5.2.0-1
	* Upload a repackaged ZIP file for Windows because of a false positive
	  virus alert by Microsoft Defender
```

**Comment by sboselli** [comment]
Publishing new release shortly.

**Comment by blightor** [comment]
You are welcome :)
